name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: pdo, sqlite3, pdo_sqlite, mbstring, dom, json, curl
        coverage: none
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Show PHP extensions (debug)
      run: php -m | grep -Ei 'sqlite|pdo' || true
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
        APP_ENV: testing
        APP_DEBUG: false
        LOG_CHANNEL: stderr
        CACHE_DRIVER: array
        SESSION_DRIVER: array
        QUEUE_CONNECTION: sync
        BROADCAST_DRIVER: log
        REDIS_HOST: 127.0.0.1
        REDIS_PASSWORD: null
        REDIS_PORT: 6379
        CI: true
      run: |
        php artisan migrate --force
        php -d display_errors=1 artisan test --stop-on-failure
    - name: Deploy
      if: github.ref == 'refs/heads/main'
      continue-on-error: true
      run: |
        if [ -n "${{ secrets.DEPLOYMENT_HOOK_URL }}" ]; then
          curl -sS -X POST "${{ secrets.DEPLOYMENT_HOOK_URL }}"
        else
          echo "No deployment hook configured"
        fi
